---
Name: simpler_silverstripe
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'daledezma/silverstripe-simpler:client/dist/styles/simpler-silverstripe.css'
  extra_requirements_javascript:
    - 'daledezma/silverstripe-simpler:client/dist/js/simpler-domevents.js'
    ## jQuery/BootstrapJS/VueJS: to opt-in, include this JS requirement in your module/project config:
#    - 'daledezma/silverstripe-simpler:client/dist/js/simpler-silverstripe.js'
